language: node_js
notifications:
  email: false
node_js:
- 6.0.0
before_install:
- travis_retry nvm install 5.5.0
- travis_retry wget https://www.dropbox.com/s/heja4ryn45bd5wt/test.tar.gz?dl=0 -O
  test.tar.gz && tar xfvz test.tar.gz
script:
- npm test
env:
  global:
  - secure: JoGSjyRNE+IppUS3xTL6cQEj6b7eN0oYmYKDZTnrzw9yEGHqb9+2ekteLS68D3mWXbmkWpXs1y+nrIacZlLX/akFm5+ruDKCPjX+ypGwTjPF/eMHBsn88Rx6y+a6LKREKb83RhkWisx2MPHtEdu4lVGXX+kFzSWtmxbe1uLr40yC1b3OuXbNRehSbobmd2NRzeXvKipg8EvzOTNYrM3wYEOkpzpjyFOCgSeT0w06RLpSmVERuoFOtm21aNUZP0p3lLXUdGcXvLKblf35zGT8csyhbwXixT2NWkry3LDf0XE9Wc93WJPPFCHawJ6qYEQ+ZJ+DLyfvFgZuO3pN4J3KLflFFr9pHP5T6MoQy2Go0WwUtYSQ0mgvlMqVg86xoCCzjbjaOGYCnAikA3kMc0DVK5m/GwIW/tdEj7sP5hX04ht3LGOtriSD+NvZUhEqXRgLa5h2C5UaYJhxVRYkl6ROo5U4S+nLYBiMkmu4uw8NOLIDhB/haP3FnNunzaFfi1pocr+zQ74rk5vAqajNWZHufBn7wVD32VxFV8kzE58ADYOI9jQv+o8S4mOXc18P11WvC6pRBgrYB/cS2RHI2qXJp3yrSsQz1TM4+6l2XnXn/ysXrpKxPBv4tpWxFNOUMVkhpbeYl67K5mOvE2KU0JexWVaQIBvhV8KeGAglT8MCNj8=
  - secure: Y1pELBjs2fHO+q/AnZDg5fa6CxbwmmZBcjdYKLxurnPzPLrr7vNYs5JqpInxqu4jj/+SmpQtJxmx3K+MSoezA0/edeyvucNCx6N9UH98kyZYwld8j65geWiPfVua98opsXaGqPTKyRwyxlX9BKuJWpG/q2YkDuAtj1c+Wf3t3W5T6kXR7x/nr2WuTSC+dy36L08O2NwpsvkEuAe205WtIzJ3EPEhsavxr4HfRNTGRCgS7ozRXH1TgRbfn/NvBGHU7iSclcJa3503SzwEoGbrJy3S9cD0VuJUHEUW7POLXJox6Zgy3/dizsRWCXFReV2JfmCLdnfFdQR33GeNHiQoR2YZwhMxZKxovAQHe2+5cbwEgUfWKvKb/m0iXKlr94HF1AwMi5kBo9546oBzFxS0IXWgys/YlxOVWHHdtlvxsDQ6I+fQx8DPV0ijtZiwJWXei2PigT0K1EeNxHG5GtWDACGkoETRPczQJwgRsykeB6+TA6G2CeYz9Kn1WgMI073pVnl68tu03AlNOYj3dfVjJNrYiZkvzuAXx/+/8R/1wcHDOQd5rYEpTBYrq+mjykWLRf5wVQS3fQuynMcaH9BYu9TyfEI7WohX9fDNT8az0Ppva+ihvmH4XwNF4OtzbaUIF/DI8UaET+X2mlx31lDIwG+RpajVBv9/vQcs8+gA2U8=
  - secure: ZnMRU2EH2Z0XZNF/px6hvFnVuPJbCZF7bHOfq3ku+ayYG4w4ho/117Pkystf3S/ONMX+xK/tR7oBRMYgZjnO8Yf0T5I1pmnQTz8QIuBks2ZIAxrgk0xNNkMveocorPBONfRHoClhpaLQyydBADyq8zoaeIRbxCUNmjMZ+ue4a5ojgDoEqIS0YJWXrSJFZpNrGqticV1s8mLwYlqFUb3aqm5RDFmdvEMr8huy76vkVZTmqR4UnBJjtAoOakAvorBhLGI8HsrL3RTu1OvZLuihJLwVYvyKQduSMSVB25C+0FmdFgAMuTrpSwMmX7HaXOMvJ5nX24sTeC9uQe0O2urZMAWgOlItN+4r6fwaFH1Zkb545ke5WeNEQlL+HR6ZoMFSoSp/e5Gu30tM0KpxYcX3c1w6r6n4DIr/juoE2TQ9zWmTtCn1HOagOXJIeInDR3jdMg7ya2niKb13Bk3iom4sCpcbwPn266QvyUOSt6ZQk6vXlcO7xCMZJEhGPGjOsl+BA/ShzN48LWSCoE86zFLASERraQnOQAOZ9gEt1L04QRtvntdLokNwsUDdw/Ahbpt/uYMGRdgW7/RVp7U6Tw6yf/PQ3x0QDsh0ROTBH4EcxyVjewHp0ZJxkUpeg2o+bFeyPcYEllWxirGAWnlWQc+YPzC0lryWEt0NwQ6xaC87dHA=
<<<<<<< HEAD
=======
  - MERGE_TOKEN=3899d0c15139b518530dc74b6077fec36ec70649
>>>>>>> c410402e0ec31ee6effc4972ecb7ba17deff095f
